//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Viewer.myWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/wcfsvc_android")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNo {
            get {
                return this.PartNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNoField, value) != true)) {
                    this.PartNoField = value;
                    this.RaisePropertyChanged("PartNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyReply", Namespace="http://schemas.datacontract.org/2004/07/wcfsvc_android")]
    [System.SerializableAttribute()]
    public partial class MyReply : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOk {
            get {
                return this.IsOkField;
            }
            set {
                if ((this.IsOkField.Equals(value) != true)) {
                    this.IsOkField = value;
                    this.RaisePropertyChanged("IsOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stock", Namespace="http://schemas.datacontract.org/2004/07/wcfsvc_android")]
    [System.SerializableAttribute()]
    public partial class Stock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OutQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RemainQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StockInField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InQty {
            get {
                return this.InQtyField;
            }
            set {
                if ((this.InQtyField.Equals(value) != true)) {
                    this.InQtyField = value;
                    this.RaisePropertyChanged("InQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocID {
            get {
                return this.LocIDField;
            }
            set {
                if ((object.ReferenceEquals(this.LocIDField, value) != true)) {
                    this.LocIDField = value;
                    this.RaisePropertyChanged("LocID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoveDate {
            get {
                return this.MoveDateField;
            }
            set {
                if ((object.ReferenceEquals(this.MoveDateField, value) != true)) {
                    this.MoveDateField = value;
                    this.RaisePropertyChanged("MoveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OutQty {
            get {
                return this.OutQtyField;
            }
            set {
                if ((this.OutQtyField.Equals(value) != true)) {
                    this.OutQtyField = value;
                    this.RaisePropertyChanged("OutQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNo {
            get {
                return this.PartNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNoField, value) != true)) {
                    this.PartNoField = value;
                    this.RaisePropertyChanged("PartNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecID {
            get {
                return this.RecIDField;
            }
            set {
                if ((this.RecIDField.Equals(value) != true)) {
                    this.RecIDField = value;
                    this.RaisePropertyChanged("RecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RemainQty {
            get {
                return this.RemainQtyField;
            }
            set {
                if ((this.RemainQtyField.Equals(value) != true)) {
                    this.RemainQtyField = value;
                    this.RaisePropertyChanged("RemainQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool StockIn {
            get {
                return this.StockInField;
            }
            set {
                if ((this.StockInField.Equals(value) != true)) {
                    this.StockInField = value;
                    this.RaisePropertyChanged("StockIn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shipment", Namespace="http://schemas.datacontract.org/2004/07/wcfsvc_android")]
    [System.SerializableAttribute()]
    public partial class Shipment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RecIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShipInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerNo {
            get {
                return this.CustomerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNoField, value) != true)) {
                    this.CustomerNoField = value;
                    this.RaisePropertyChanged("CustomerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderNoField, value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNo {
            get {
                return this.PartNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNoField, value) != true)) {
                    this.PartNoField = value;
                    this.RaisePropertyChanged("PartNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RecID {
            get {
                return this.RecIDField;
            }
            set {
                if ((this.RecIDField.Equals(value) != true)) {
                    this.RecIDField = value;
                    this.RaisePropertyChanged("RecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipDate {
            get {
                return this.ShipDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipDateField, value) != true)) {
                    this.ShipDateField = value;
                    this.RaisePropertyChanged("ShipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShipIn {
            get {
                return this.ShipInField;
            }
            set {
                if ((this.ShipInField.Equals(value) != true)) {
                    this.ShipInField = value;
                    this.RaisePropertyChanged("ShipIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipNo {
            get {
                return this.ShipNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipNoField, value) != true)) {
                    this.ShipNoField = value;
                    this.RaisePropertyChanged("ShipNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierNo {
            get {
                return this.SupplierNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNoField, value) != true)) {
                    this.SupplierNoField = value;
                    this.RaisePropertyChanged("SupplierNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/aics/", ConfigurationName="myWCF.IWcfSvcICS")]
    public interface IWcfSvcICS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetProducts", ReplyAction="http://localhost/aics/IWcfSvcICS/GetProductsResponse")]
        System.Collections.Generic.List<Data_Viewer.myWCF.Product> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetProducts", ReplyAction="http://localhost/aics/IWcfSvcICS/GetProductsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Product>> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/CheckConn", ReplyAction="http://localhost/aics/IWcfSvcICS/CheckConnResponse")]
        Data_Viewer.myWCF.MyReply CheckConn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/CheckConn", ReplyAction="http://localhost/aics/IWcfSvcICS/CheckConnResponse")]
        System.Threading.Tasks.Task<Data_Viewer.myWCF.MyReply> CheckConnAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetDbInfo", ReplyAction="http://localhost/aics/IWcfSvcICS/GetDbInfoResponse")]
        Data_Viewer.myWCF.MyReply GetDbInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetDbInfo", ReplyAction="http://localhost/aics/IWcfSvcICS/GetDbInfoResponse")]
        System.Threading.Tasks.Task<Data_Viewer.myWCF.MyReply> GetDbInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetProduct", ReplyAction="http://localhost/aics/IWcfSvcICS/GetProductResponse")]
        Data_Viewer.myWCF.Product GetProduct(string partNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetProduct", ReplyAction="http://localhost/aics/IWcfSvcICS/GetProductResponse")]
        System.Threading.Tasks.Task<Data_Viewer.myWCF.Product> GetProductAsync(string partNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetProductByLoc", ReplyAction="http://localhost/aics/IWcfSvcICS/GetProductByLocResponse")]
        System.Collections.Generic.List<Data_Viewer.myWCF.Stock> GetProductByLoc(string locID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetProductByLoc", ReplyAction="http://localhost/aics/IWcfSvcICS/GetProductByLocResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Stock>> GetProductByLocAsync(string locID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetShipmentByInput", ReplyAction="http://localhost/aics/IWcfSvcICS/GetShipmentByInputResponse")]
        System.Collections.Generic.List<Data_Viewer.myWCF.Stock> GetShipmentByInput(string input1, string input2, string inOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetShipmentByInput", ReplyAction="http://localhost/aics/IWcfSvcICS/GetShipmentByInputResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Stock>> GetShipmentByInputAsync(string input1, string input2, string inOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetAllStock", ReplyAction="http://localhost/aics/IWcfSvcICS/GetAllStockResponse")]
        System.Collections.Generic.List<Data_Viewer.myWCF.Stock> GetAllStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetAllStock", ReplyAction="http://localhost/aics/IWcfSvcICS/GetAllStockResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Stock>> GetAllStockAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetAllShipment", ReplyAction="http://localhost/aics/IWcfSvcICS/GetAllShipmentResponse")]
        System.Collections.Generic.List<Data_Viewer.myWCF.Shipment> GetAllShipment();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetAllShipment", ReplyAction="http://localhost/aics/IWcfSvcICS/GetAllShipmentResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Shipment>> GetAllShipmentAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetQtyByLocPart", ReplyAction="http://localhost/aics/IWcfSvcICS/GetQtyByLocPartResponse")]
        int GetQtyByLocPart(string locID, string partNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/GetQtyByLocPart", ReplyAction="http://localhost/aics/IWcfSvcICS/GetQtyByLocPartResponse")]
        System.Threading.Tasks.Task<int> GetQtyByLocPartAsync(string locID, string partNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/StockIO", ReplyAction="http://localhost/aics/IWcfSvcICS/StockIOResponse")]
        Data_Viewer.myWCF.MyReply StockIO(Data_Viewer.myWCF.Stock moveStk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/StockIO", ReplyAction="http://localhost/aics/IWcfSvcICS/StockIOResponse")]
        System.Threading.Tasks.Task<Data_Viewer.myWCF.MyReply> StockIOAsync(Data_Viewer.myWCF.Stock moveStk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/ShipmentIO", ReplyAction="http://localhost/aics/IWcfSvcICS/ShipmentIOResponse")]
        Data_Viewer.myWCF.MyReply ShipmentIO(Data_Viewer.myWCF.Shipment shipStk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/aics/IWcfSvcICS/ShipmentIO", ReplyAction="http://localhost/aics/IWcfSvcICS/ShipmentIOResponse")]
        System.Threading.Tasks.Task<Data_Viewer.myWCF.MyReply> ShipmentIOAsync(Data_Viewer.myWCF.Shipment shipStk);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfSvcICSChannel : Data_Viewer.myWCF.IWcfSvcICS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfSvcICSClient : System.ServiceModel.ClientBase<Data_Viewer.myWCF.IWcfSvcICS>, Data_Viewer.myWCF.IWcfSvcICS {
        
        public WcfSvcICSClient() {
        }
        
        public WcfSvcICSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfSvcICSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfSvcICSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfSvcICSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Data_Viewer.myWCF.Product> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Product>> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public Data_Viewer.myWCF.MyReply CheckConn() {
            return base.Channel.CheckConn();
        }
        
        public System.Threading.Tasks.Task<Data_Viewer.myWCF.MyReply> CheckConnAsync() {
            return base.Channel.CheckConnAsync();
        }
        
        public Data_Viewer.myWCF.MyReply GetDbInfo() {
            return base.Channel.GetDbInfo();
        }
        
        public System.Threading.Tasks.Task<Data_Viewer.myWCF.MyReply> GetDbInfoAsync() {
            return base.Channel.GetDbInfoAsync();
        }
        
        public Data_Viewer.myWCF.Product GetProduct(string partNo) {
            return base.Channel.GetProduct(partNo);
        }
        
        public System.Threading.Tasks.Task<Data_Viewer.myWCF.Product> GetProductAsync(string partNo) {
            return base.Channel.GetProductAsync(partNo);
        }
        
        public System.Collections.Generic.List<Data_Viewer.myWCF.Stock> GetProductByLoc(string locID) {
            return base.Channel.GetProductByLoc(locID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Stock>> GetProductByLocAsync(string locID) {
            return base.Channel.GetProductByLocAsync(locID);
        }
        
        public System.Collections.Generic.List<Data_Viewer.myWCF.Stock> GetShipmentByInput(string input1, string input2, string inOut) {
            return base.Channel.GetShipmentByInput(input1, input2, inOut);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Stock>> GetShipmentByInputAsync(string input1, string input2, string inOut) {
            return base.Channel.GetShipmentByInputAsync(input1, input2, inOut);
        }
        
        public System.Collections.Generic.List<Data_Viewer.myWCF.Stock> GetAllStock() {
            return base.Channel.GetAllStock();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Stock>> GetAllStockAsync() {
            return base.Channel.GetAllStockAsync();
        }
        
        public System.Collections.Generic.List<Data_Viewer.myWCF.Shipment> GetAllShipment() {
            return base.Channel.GetAllShipment();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Data_Viewer.myWCF.Shipment>> GetAllShipmentAsync() {
            return base.Channel.GetAllShipmentAsync();
        }
        
        public int GetQtyByLocPart(string locID, string partNo) {
            return base.Channel.GetQtyByLocPart(locID, partNo);
        }
        
        public System.Threading.Tasks.Task<int> GetQtyByLocPartAsync(string locID, string partNo) {
            return base.Channel.GetQtyByLocPartAsync(locID, partNo);
        }
        
        public Data_Viewer.myWCF.MyReply StockIO(Data_Viewer.myWCF.Stock moveStk) {
            return base.Channel.StockIO(moveStk);
        }
        
        public System.Threading.Tasks.Task<Data_Viewer.myWCF.MyReply> StockIOAsync(Data_Viewer.myWCF.Stock moveStk) {
            return base.Channel.StockIOAsync(moveStk);
        }
        
        public Data_Viewer.myWCF.MyReply ShipmentIO(Data_Viewer.myWCF.Shipment shipStk) {
            return base.Channel.ShipmentIO(shipStk);
        }
        
        public System.Threading.Tasks.Task<Data_Viewer.myWCF.MyReply> ShipmentIOAsync(Data_Viewer.myWCF.Shipment shipStk) {
            return base.Channel.ShipmentIOAsync(shipStk);
        }
    }
}
